---
title: "c:call-template"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:call-template</span>
  <b>name</b> = <i title="An EQName. Unprefixed QNames are in the null namespace.">EQName</i> &gt;
  &lt;!-- Content: <span><a href="with-param.html">c:with-param</a>*</span> --&gt;
<span class="nt">&lt;/c:call-template&gt;</span></code></pre></div>
<dl>
   <dt><b>Category</b></dt>
   <dd><i>instruction</i></dd>
   <dt><b>Permitted parent elements</b></dt>
   <dd>Any XCST element whose content model is <i>sequence-constructor</i></dd>
   <dd>Any literal result element</dd>
</dl>
<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:call-template</span>
  <b>name</b> = { <i title="An EQName. Unprefixed QNames are in the null namespace.">EQName</i> }
  <span>with-params</span>? = <i title="Expression">Expression</i> &gt;
  &lt;!-- Content: <span><a href="with-param.html">c:with-param</a>*</span> --&gt;
<span class="nt">&lt;/c:call-template&gt;</span></code></pre></div>
<dl>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="using-module.html">c:using-module</a></dd>
</dl>