---
title: "c:element"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:element</span>
  <b>name</b> = { <i title="A QName. Unprefixed names are in the default namespace.">QName</i> }
  <span>namespace</span>? = { <i>URI</i> }
  <span>use-attribute-sets</span>? = <span><i title="An EQName. Unprefixed QNames are in the null namespace.">EQName</i>*</span> &gt;
  &lt;!-- Content: <i>sequence-constructor</i> --&gt;
<span class="nt">&lt;/c:element&gt;</span></code></pre></div>
<dl>
   <dt><b>Category</b></dt>
   <dd><i>instruction</i></dd>
   <dt><b>Permitted parent elements</b></dt>
   <dd>Any XCST element whose content model is <i>sequence-constructor</i></dd>
   <dd>Any literal result element</dd>
</dl>