---
title: "c:override"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:override</span>&gt;
  &lt;!-- Content: <span><span>(<a href="template.html">c:template</a> | <a href="function.html">c:function</a> | <a href="variable.html">c:variable</a> | <a href="param.html">c:param</a> | <a href="attribute-set.html">c:attribute-set</a> | <a href="type.html">c:type</a>)</span>*</span> --&gt;
<span class="nt">&lt;/c:override&gt;</span></code></pre></div>
<dl>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="use-package.html">c:use-package</a></dd>
</dl>