---
title: "c:use-package"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:use-package</span>
  <b>name</b> = <i>Name</i> &gt;
  &lt;!-- Content: <span><a href="override.html">c:override</a>*</span> --&gt;
<span class="nt">&lt;/c:use-package&gt;</span></code></pre></div>
<dl>
   <dt><b>Category</b></dt>
   <dd><i>declaration</i></dd>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="module.html">c:module</a></dd>
   <dd><a href="package.html">c:package</a></dd>
</dl>