---
title: "c:with-param"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:with-param</span>
  <b>name</b> = <i>Name</i>
  <span>as</span>? = <i>Type</i>
  <span>tunnel</span>? = <i title="One of the values &#34;yes&#34;, &#34;no&#34;, &#34;true&#34;, &#34;false&#34;, &#34;1&#34; or &#34;0&#34;.">Boolean</i>
  <span>value</span>? = <i title="Expression">Expression</i> &gt;
  &lt;!-- Content: <span><i>sequence-constructor</i></span> --&gt;
<span class="nt">&lt;/c:with-param&gt;</span></code></pre></div>
<dl>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="call-template.html">c:call-template</a></dd>
   <dd><a href="evaluate-delegate.html">c:evaluate-delegate</a></dd>
   <dd><a href="next-template.html">c:next-template</a></dd>
   <dd><a href="using-module.html">c:using-module</a></dd>
</dl>
<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;c:with-param</span>
  <span>name</span>? = <i>Name</i>
  <span>as</span>? = <i>Type</i>
  <span>tunnel</span>? = <i title="One of the values &#34;yes&#34;, &#34;no&#34;, &#34;true&#34;, &#34;false&#34;, &#34;1&#34; or &#34;0&#34;.">Boolean</i>
  <span>value</span>? = <i title="Expression">Expression</i> &gt;
  &lt;!-- Content: <span><i>sequence-constructor</i></span> --&gt;
<span class="nt">&lt;/c:with-param&gt;</span></code></pre></div>
<dl>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="next-function.html">c:next-function</a></dd>
</dl>