title: Declarative Programming
author: Max Toro
url: http://maxtoroq.github.io
feed: http://feeds.feedburner.com/maxtoroq
timezone: America/Santiago
permalink: /:year/:month/:title.html

markdown: redcarpet
