title: Declarative Programming
author: Max Toro
url: http://maxtoroq.github.io
feed: /feed.xml
timezone: America/Santiago
permalink: /:year/:month/:title.html

sass:
  style: compressed

gems:
   - jemoji

defaults:
   -
      scope:
         path: ""
         type: post
      values:
         layout: post
   -
      scope:
         path: ""
         type: page
      values:
         layout: page
   -
      scope:
         path: "DbExtensions"
         type: page
      values:
         layout: DbExtensions
         repository_url: https://github.com/maxtoroq/DbExtensions
   -
      scope:
         path: "MvcAccount"
         type: page
      values:
         layout: MvcAccount
         repository_url: https://github.com/maxtoroq/MvcAccount
   -
      scope:
         path: "MvcPages"
         type: page
      values:
         layout: MvcPages
         repository_url: https://github.com/maxtoroq/MvcPages
   -
      scope:
         path: "myxsl"
         type: page
      values:
         layout: myxsl
         base_url: "/myxsl/"
         repository_url: https://github.com/maxtoroq/myxsl
   -
      scope:
         path: "XCST"
         type: page
      values:
         layout: XCST
         base_url: /XCST/
         repository_url: https://github.com/maxtoroq/XCST
         documentation_url: /XCST/docs/
         support_url: https://github.com/maxtoroq/XCST/issues?q=is%3Aissue+label%3Aquestion
