title: maxtoroq
author: Max Toro Q.
url: https://maxtoroq.github.io
timezone: America/Santiago
permalink: /:year/:month/:title:output_ext

sass:
  style: compressed

plugins:
  - jemoji

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: pages
    values:
      layout: page

  - scope:
      path: DbExtensions
      type: pages
    values:
      layout: DbExtensions-docs
      repository_url: https://github.com/maxtoroq/DbExtensions
      support_url: https://github.com/maxtoroq/DbExtensions/discussions

  - scope:
      path: DbExtensions/docs
      type: pages
    values:
      toc: DbExtensions_toc
      toc_base_url: /DbExtensions/docs/

  - scope:
      path: DbExtensions/docs/api
      type: pages
    values:
      toc: DbExtensions_api_toc
      toc_base_url: /DbExtensions/docs/api/

  - scope:
      path: MvcCodeRouting
      type: pages
    values:
      layout: MvcCodeRouting
      base_url: /MvcCodeRouting/
      repository_url: https://github.com/maxtoroq/MvcCodeRouting
      documentation_url: https://github.com/maxtoroq/MvcCodeRouting/blob/master/docs/README.md

  - scope:
      path: myxsl
      type: pages
    values:
      base_url: https://github.com/maxtoroq/myxsl
      repository_url: https://github.com/maxtoroq/myxsl

  - scope:
      path: XCST
      type: pages
    values:
      layout: XCST-docs
      repository_url: https://github.com/maxtoroq/XCST
      documentation_url: /XCST/docs/
      support_url: https://github.com/maxtoroq/XCST/discussions
      bcl_url: https://msdn.microsoft.com/en-us/library/
      csharp_spec_url: https://github.com/dotnet/csharplang/blob/main/spec/

  - scope:
      path: XCST/docs
      type: pages
    values:
      toc: XCST_toc
      toc_base_url: /XCST/docs/
      edit_link: true

  - scope:
      path: XCST/c
      type: pages
    values:
      toc: XCST_elements_toc
      toc_base_url: /XCST/
      element_ref: true
      left_nav: true
      edit_link: true

  - scope:
      path: XCST/a
      type: pages
    values:
      toc: XCST_elements_toc
      toc_base_url: /XCST/
      element_ref: true
      left_nav: true
      edit_link: true

include:
  # DbExtensions
  - _ctor.md
  - _ctor_?.md
  - _.md
  - _ForEach_*.md
  - _If.md
  - _OR_*.md
