---
title: "a:display"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;a:display</span>
  <span>for</span>? = <i title="Expression">Expression</i>
  <span>name</span>? = { <i>String</i> }
  <span>template</span>? = { <i>String</i> }
  <span>html-field-name</span>? = { <i>String</i> }
  <span>html-attributes</span>? = <i title="Expression">Expression</i>
  <span>with-params</span>? = <i title="Expression">Expression</i>
  <span>options</span>? = <i title="Expression">Expression</i> &gt;
  &lt;!-- Content: (<span><a href="with-options.html">a:with-options</a>*</span>, <span><a href="member-template.html">a:member-template</a>?</span>) --&gt;
<span class="nt">&lt;/a:display&gt;</span></code></pre></div>
<dl>
   <dt><b>Category</b></dt>
   <dd><i>instruction</i></dd>
   <dt><b>Permitted parent elements</b></dt>
   <dd>Any XCST element whose content model is <i>sequence-constructor</i></dd>
   <dd>Any literal result element</dd>
</dl>