---
title: "a:label"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;a:label</span>
  <span>for</span>? = <i title="Expression">Expression</i>
  <span>name</span>? = { <i>String</i> }
  <span>text</span>? = { <i>String</i> }
  <span>html-class</span>? = { <i>String</i> }
  <span>html-attributes</span>? = <i title="Expression">Expression</i> /&gt;</code></pre></div>
<dl>
   <dt><b>Category</b></dt>
   <dd><i>instruction</i></dd>
   <dt><b>Permitted parent elements</b></dt>
   <dd>Any XCST element whose content model is <i>sequence-constructor</i></dd>
   <dd>Any literal result element</dd>
</dl>