---
title: "a:member-template"
---

{% comment %}
This page was generated by a tool.

Changes to this file may cause incorrect behavior and will be lost if
the page is regenerated.
{% endcomment %}

<div class="language-xml highlighter-rouge"><pre class="highlight element-syntax"><code><span class="nt">&lt;a:member-template</span>
  <span>helper-name</span>? = <i>Name</i> &gt;
  &lt;!-- Content: <i>sequence-constructor</i> --&gt;
<span class="nt">&lt;/a:member-template&gt;</span></code></pre></div>
<dl>
   <dt><b>Permitted parent elements</b></dt>
   <dd><a href="display.html">a:display</a></dd>
   <dd><a href="editor.html">a:editor</a></dd>
</dl>